apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-app-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/AhmetKutlu/Pulumi-AKS-ArgoCD.git
    targetRevision: HEAD
    path: argo-cd-apps/mysql
    helm:
      valueFiles:
        - values-prod.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
